# ansible/playbooks/deploy.yml
- hosts: all

  tasks:
    - name: Login to Vultr registry
      shell: docker login https://ewr.vultrcr.com/autodeploy -u "{{ vultr_username }}" -p "{{ vultr_api_key }}"

    - name: Pull the image
      shell: docker pull "ewr.vultrcr.com/autodeploy/{{image_name}}:{{image_tag}}"

    - name: Delete existing container if it exists
      shell: docker container rm -f {{container_name}} || true

    - name: Include all secrets
      include_vars: secrets.yml

    - name: Deploy container
      shell: >
        docker run
        --network ingress-network
        -e NEXT_PUBLIC_API_URL="{{ next_public_api_url }}"
        -e NEXT_DATABASE_URL="{{ next_database_url }}"
        --name {{container_name}}
        --restart unless-stopped
        -d "ewr.vultrcr.com/autodeploy/{{image_name}}:{{image_tag}}"

    - name: Clean up old images
      shell: docker image prune -f