name: Deploy to Vultr

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Building:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Image Name
        id: image-name
        shell: bash
        run: echo "name=vultr_web" >> $GITHUB_OUTPUT

      - name: Login to Vultr Container Registry
        uses: docker/login-action@v2
        with:
          registry: ewr.vultrcr.com/autodeploy
          username: ${{ secrets.VULTR_USERNAME }}
          password: ${{ secrets.VULTR_API_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ewr.vultrcr.com/autodeploy/${{ steps.image-name.outputs.name }}:${{ github.sha }}

  Deploying:
    needs: Building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Container Name
        id: container-name
        shell: bash
        run: echo "name=vultr_web" >> $GITHUB_OUTPUT

      - name: Container Port
        id: container-port
        shell: bash
        run: echo "port=3000" >> $GITHUB_OUTPUT

      - name: Set secrets.yml from Github Secret
        run: echo "${{ secrets.PROD_ANSIBLE_SECRETS }}" | openssl enc -d -base64 | tee ansible/playbooks/secrets.yml

      - name: Deploy Container
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbooks/deploy.yml
          directory: ${{ github.workspace }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            vultr_server:
              hosts:
                vars:
                  ansible_host: ${{ secrets.VULTR_HOST }}
                  ansible_user: root
                  image_tag: ${{ github.sha }}
                  image_name: vultr_web
                  container_name: ${{ steps.container-name.outputs.name }}
                  container_port: ${{ steps.container-port.outputs.port }}
                  vultr_username: ${{ secrets.VULTR_USERNAME }}
                  vultr_api_key: ${{ secrets.VULTR_API_KEY }}            